- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    nonsecret: "Hello from playbook variable"

  tasks:
  - template:
      src: resources/secret-file-for-template.txt
      dest: /tmp/secret-file-for-template-decrypted.txt
  