- hosts: 
  - centos
  - debian

  pre_tasks:
  - shell: echo 'Start'
  
  #roles:
  #- java
  #- tomcat

  tasks:
  - shell: echo 'Running'

  post_tasks:
  - shell: echo 'Finish'
  
  ========================================
  - hosts: all   # perform all tasks from root
    become: yes
    become_user: build  # perfom from some user
  
